##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= dashboard

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -Og

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/adc.c \
Core/Src/bsp.c \
Core/Src/button.c \
Core/Src/can.c \
Core/Src/dac.c \
Core/Src/dashboard.c \
Core/Src/dma.c \
Core/Src/gpio.c \
Core/Src/i2c.c \
Core/Src/main.c \
Core/Src/spi.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32f4xx.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/utils.c \
Core/Src/wdg.c \
Drivers/ILI9488/ili9488.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
EEZ/global_vars.c \
EEZ/screen_loader.c \
EEZ/src/ui/images.c \
EEZ/src/ui/screens.c \
EEZ/src/ui/styles.c \
EEZ/src/ui/ui.c \
Lib/LVGL/callback/callback.c \
Lib/LVGL/log/log.c \
Lib/LVGL/lvgl/demos/benchmark/assets/img_benchmark_avatar.c \
Lib/LVGL/lvgl/demos/benchmark/assets/img_benchmark_lvgl_logo_argb.c \
Lib/LVGL/lvgl/demos/benchmark/assets/img_benchmark_lvgl_logo_rgb.c \
Lib/LVGL/lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_12_compr_az.c.c \
Lib/LVGL/lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_16_compr_az.c.c \
Lib/LVGL/lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_28_compr_az.c.c \
Lib/LVGL/lvgl/demos/benchmark/lv_demo_benchmark.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_130.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_56.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_inter_14.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_inter_20.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_trump_24.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_trump_40.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_trump_48.c \
Lib/LVGL/lvgl/demos/ebike/generated/font_ebike_trump_72.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_arrow_left.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_arrow_left_2.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_arrow_right.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_arrow_right_2.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_bg.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_bg_large.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_clock.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_dropdown_icon.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_home.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_lamp.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_scale.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_scale_large.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_settings.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_settings_large.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_stats.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_stats_large.c \
Lib/LVGL/lvgl/demos/ebike/generated/img_ebike_whether.c \
Lib/LVGL/lvgl/demos/ebike/generated/lottie_ebike_settings.c \
Lib/LVGL/lvgl/demos/ebike/generated/lottie_ebike_stats.c \
Lib/LVGL/lvgl/demos/ebike/lv_demo_ebike.c \
Lib/LVGL/lvgl/demos/ebike/lv_demo_ebike_home.c \
Lib/LVGL/lvgl/demos/ebike/lv_demo_ebike_settings.c \
Lib/LVGL/lvgl/demos/ebike/lv_demo_ebike_stats.c \
Lib/LVGL/lvgl/demos/ebike/translations/lv_i18n.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_ctrl_pad.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_flex_loader.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_main.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_view.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_view_child_node.c \
Lib/LVGL/lvgl/demos/flex_layout/lv_demo_flex_layout_view_ctrl_pad.c \
Lib/LVGL/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
Lib/LVGL/lvgl/demos/lv_demos.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_1.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_10.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_11.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_12.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_13.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_14.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_15.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_16.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_17.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_18.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_19.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_2.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_22.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_25.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_3.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_4.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_5.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_6.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_7.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_8.c \
Lib/LVGL/lvgl/demos/multilang/assets/avatars/img_multilang_avatar_9.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_artist_palette.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_books.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_camera_with_flash.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_cat_face.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_deciduous_tree.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_dog_face.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_earth_globe_europe_africa.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_flexed_biceps.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_movie_camera.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_red_heart.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_rocket.c \
Lib/LVGL/lvgl/demos/multilang/assets/emojis/img_emoji_soccer_ball.c \
Lib/LVGL/lvgl/demos/multilang/assets/fonts/font_multilang_large.c \
Lib/LVGL/lvgl/demos/multilang/assets/fonts/font_multilang_small.c \
Lib/LVGL/lvgl/demos/multilang/assets/img_multilang_like.c \
Lib/LVGL/lvgl/demos/multilang/lv_demo_multilang.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_logo.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
Lib/LVGL/lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
Lib/LVGL/lvgl/demos/music/lv_demo_music.c \
Lib/LVGL/lvgl/demos/music/lv_demo_music_list.c \
Lib/LVGL/lvgl/demos/music/lv_demo_music_main.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_arc_bg.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_argb8888.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_i1.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_l8.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_rgb565.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_rgb565a8.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_rgb888.c \
Lib/LVGL/lvgl/demos/render/assets/img_render_lvgl_logo_xrgb8888.c \
Lib/LVGL/lvgl/demos/render/lv_demo_render.c \
Lib/LVGL/lvgl/demos/scroll/lv_demo_scroll.c \
Lib/LVGL/lvgl/demos/stress/lv_demo_stress.c \
Lib/LVGL/lvgl/demos/transform/assets/img_transform_avatar_15.c \
Lib/LVGL/lvgl/demos/transform/lv_demo_transform.c \
Lib/LVGL/lvgl/demos/vector_graphic/assets/img_demo_vector_avatar.c \
Lib/LVGL/lvgl/demos/vector_graphic/lv_demo_vector_graphic.c \
Lib/LVGL/lvgl/demos/widgets/assets/img_clothes.c \
Lib/LVGL/lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
Lib/LVGL/lvgl/demos/widgets/assets/img_demo_widgets_needle.c \
Lib/LVGL/lvgl/demos/widgets/assets/img_lvgl_logo.c \
Lib/LVGL/lvgl/demos/widgets/lv_demo_widgets.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lv_point_t.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lv_timer_t.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lv_wegit.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lvgl.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lvgl_indev_t.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lvgl_lv_event.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lvgl_lv_obj.c \
Lib/LVGL/lvgl/env_support/pikascript/pika_lvgl_lv_style_t.c \
Lib/LVGL/lvgl/env_support/rt-thread/lv_rt_thread_port.c \
Lib/LVGL/lvgl/env_support/rt-thread/squareline/lv_ui_entry.c \
Lib/LVGL/lvgl/src/core/lv_group.c \
Lib/LVGL/lvgl/src/core/lv_obj.c \
Lib/LVGL/lvgl/src/core/lv_obj_class.c \
Lib/LVGL/lvgl/src/core/lv_obj_draw.c \
Lib/LVGL/lvgl/src/core/lv_obj_event.c \
Lib/LVGL/lvgl/src/core/lv_obj_id_builtin.c \
Lib/LVGL/lvgl/src/core/lv_obj_pos.c \
Lib/LVGL/lvgl/src/core/lv_obj_property.c \
Lib/LVGL/lvgl/src/core/lv_obj_scroll.c \
Lib/LVGL/lvgl/src/core/lv_obj_style.c \
Lib/LVGL/lvgl/src/core/lv_obj_style_gen.c \
Lib/LVGL/lvgl/src/core/lv_obj_tree.c \
Lib/LVGL/lvgl/src/core/lv_refr.c \
Lib/LVGL/lvgl/src/display/lv_display.c \
Lib/LVGL/lvgl/src/draw/dma2d/lv_draw_dma2d.c \
Lib/LVGL/lvgl/src/draw/dma2d/lv_draw_dma2d_fill.c \
Lib/LVGL/lvgl/src/draw/dma2d/lv_draw_dma2d_img.c \
Lib/LVGL/lvgl/src/draw/lv_draw.c \
Lib/LVGL/lvgl/src/draw/lv_draw_arc.c \
Lib/LVGL/lvgl/src/draw/lv_draw_buf.c \
Lib/LVGL/lvgl/src/draw/lv_draw_image.c \
Lib/LVGL/lvgl/src/draw/lv_draw_label.c \
Lib/LVGL/lvgl/src/draw/lv_draw_line.c \
Lib/LVGL/lvgl/src/draw/lv_draw_mask.c \
Lib/LVGL/lvgl/src/draw/lv_draw_rect.c \
Lib/LVGL/lvgl/src/draw/lv_draw_triangle.c \
Lib/LVGL/lvgl/src/draw/lv_draw_vector.c \
Lib/LVGL/lvgl/src/draw/lv_image_decoder.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_arc.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_border.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_fill.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_img.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_layer.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_line.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_stm32_hal.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_triangle.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_utils.c \
Lib/LVGL/lvgl/src/draw/nema_gfx/lv_nema_gfx_path.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_draw_buf_pxp.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp_fill.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp_img.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp_layer.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_pxp_cfg.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_pxp_osa.c \
Lib/LVGL/lvgl/src/draw/nxp/pxp/lv_pxp_utils.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_buf_vglite.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_border.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_fill.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_img.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_label.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_layer.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_triangle.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_matrix.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_path.c \
Lib/LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
Lib/LVGL/lvgl/src/draw/opengles/lv_draw_opengles.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
Lib/LVGL/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
Lib/LVGL/lvgl/src/draw/sdl/lv_draw_sdl.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_al88.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_i1.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_l8.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
Lib/LVGL/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_arc.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_border.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_fill.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_img.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_letter.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_line.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_mask.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_mask_rect.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_transform.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_triangle.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_utils.c \
Lib/LVGL/lvgl/src/draw/sw/lv_draw_sw_vector.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_buf_vg_lite.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_arc.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_border.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_fill.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_img.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_label.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_layer.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_line.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_triangle.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_draw_vg_lite_vector.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_decoder.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_grad.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_math.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_path.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_pending.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_stroke.c \
Lib/LVGL/lvgl/src/draw/vg_lite/lv_vg_lite_utils.c \
Lib/LVGL/lvgl/src/drivers/display/drm/lv_linux_drm.c \
Lib/LVGL/lvgl/src/drivers/display/fb/lv_linux_fbdev.c \
Lib/LVGL/lvgl/src/drivers/display/ili9341/lv_ili9341.c \
Lib/LVGL/lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.c \
Lib/LVGL/lvgl/src/drivers/display/renesas_glcdc/lv_renesas_glcdc.c \
Lib/LVGL/lvgl/src/drivers/display/st7735/lv_st7735.c \
Lib/LVGL/lvgl/src/drivers/display/st7789/lv_st7789.c \
Lib/LVGL/lvgl/src/drivers/display/st7796/lv_st7796.c \
Lib/LVGL/lvgl/src/drivers/display/st_ltdc/lv_st_ltdc.c \
Lib/LVGL/lvgl/src/drivers/evdev/lv_evdev.c \
Lib/LVGL/lvgl/src/drivers/glfw/lv_glfw_window.c \
Lib/LVGL/lvgl/src/drivers/glfw/lv_opengles_debug.c \
Lib/LVGL/lvgl/src/drivers/glfw/lv_opengles_driver.c \
Lib/LVGL/lvgl/src/drivers/glfw/lv_opengles_texture.c \
Lib/LVGL/lvgl/src/drivers/libinput/lv_libinput.c \
Lib/LVGL/lvgl/src/drivers/libinput/lv_xkb.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_cache.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_entry.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_fbdev.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_image_cache.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_lcd.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_libuv.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_profiler.c \
Lib/LVGL/lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.c \
Lib/LVGL/lvgl/src/drivers/qnx/lv_qnx.c \
Lib/LVGL/lvgl/src/drivers/sdl/lv_sdl_keyboard.c \
Lib/LVGL/lvgl/src/drivers/sdl/lv_sdl_mouse.c \
Lib/LVGL/lvgl/src/drivers/sdl/lv_sdl_mousewheel.c \
Lib/LVGL/lvgl/src/drivers/sdl/lv_sdl_window.c \
Lib/LVGL/lvgl/src/drivers/wayland/lv_wayland.c \
Lib/LVGL/lvgl/src/drivers/wayland/lv_wayland_smm.c \
Lib/LVGL/lvgl/src/drivers/windows/lv_windows_context.c \
Lib/LVGL/lvgl/src/drivers/windows/lv_windows_display.c \
Lib/LVGL/lvgl/src/drivers/windows/lv_windows_input.c \
Lib/LVGL/lvgl/src/drivers/x11/lv_x11_display.c \
Lib/LVGL/lvgl/src/drivers/x11/lv_x11_input.c \
Lib/LVGL/lvgl/src/font/lv_binfont_loader.c \
Lib/LVGL/lvgl/src/font/lv_font.c \
Lib/LVGL/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
Lib/LVGL/lvgl/src/font/lv_font_fmt_txt.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_10.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_12.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_14.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_16.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_18.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_20.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_22.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_24.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_26.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_28.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_28_compressed.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_30.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_32.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_34.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_36.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_38.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_40.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_42.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_44.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_46.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_48.c \
Lib/LVGL/lvgl/src/font/lv_font_montserrat_8.c \
Lib/LVGL/lvgl/src/font/lv_font_simsun_14_cjk.c \
Lib/LVGL/lvgl/src/font/lv_font_simsun_16_cjk.c \
Lib/LVGL/lvgl/src/font/lv_font_unscii_16.c \
Lib/LVGL/lvgl/src/font/lv_font_unscii_8.c \
Lib/LVGL/lvgl/src/indev/lv_indev.c \
Lib/LVGL/lvgl/src/indev/lv_indev_gesture.c \
Lib/LVGL/lvgl/src/indev/lv_indev_scroll.c \
Lib/LVGL/lvgl/src/layouts/flex/lv_flex.c \
Lib/LVGL/lvgl/src/layouts/grid/lv_grid.c \
Lib/LVGL/lvgl/src/layouts/lv_layout.c \
Lib/LVGL/lvgl/src/libs/barcode/code128.c \
Lib/LVGL/lvgl/src/libs/barcode/lv_barcode.c \
Lib/LVGL/lvgl/src/libs/bin_decoder/lv_bin_decoder.c \
Lib/LVGL/lvgl/src/libs/bmp/lv_bmp.c \
Lib/LVGL/lvgl/src/libs/expat/xmlparse.c \
Lib/LVGL/lvgl/src/libs/expat/xmlrole.c \
Lib/LVGL/lvgl/src/libs/expat/xmltok.c \
Lib/LVGL/lvgl/src/libs/expat/xmltok_impl.c \
Lib/LVGL/lvgl/src/libs/expat/xmltok_ns.c \
Lib/LVGL/lvgl/src/libs/ffmpeg/lv_ffmpeg.c \
Lib/LVGL/lvgl/src/libs/freetype/lv_freetype.c \
Lib/LVGL/lvgl/src/libs/freetype/lv_freetype_glyph.c \
Lib/LVGL/lvgl/src/libs/freetype/lv_freetype_image.c \
Lib/LVGL/lvgl/src/libs/freetype/lv_freetype_outline.c \
Lib/LVGL/lvgl/src/libs/freetype/lv_ftsystem.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_cbfs.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_fatfs.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_littlefs.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_memfs.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_posix.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_stdio.c \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_win32.c \
Lib/LVGL/lvgl/src/libs/gif/gifdec.c \
Lib/LVGL/lvgl/src/libs/gif/lv_gif.c \
Lib/LVGL/lvgl/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c \
Lib/LVGL/lvgl/src/libs/libpng/lv_libpng.c \
Lib/LVGL/lvgl/src/libs/lodepng/lodepng.c \
Lib/LVGL/lvgl/src/libs/lodepng/lv_lodepng.c \
Lib/LVGL/lvgl/src/libs/lz4/lz4.c \
Lib/LVGL/lvgl/src/libs/qrcode/lv_qrcode.c \
Lib/LVGL/lvgl/src/libs/qrcode/qrcodegen.c \
Lib/LVGL/lvgl/src/libs/rle/lv_rle.c \
Lib/LVGL/lvgl/src/libs/rlottie/lv_rlottie.c \
Lib/LVGL/lvgl/src/libs/svg/lv_svg.c \
Lib/LVGL/lvgl/src/libs/svg/lv_svg_parser.c \
Lib/LVGL/lvgl/src/libs/svg/lv_svg_render.c \
Lib/LVGL/lvgl/src/libs/svg/lv_svg_token.c \
Lib/LVGL/lvgl/src/libs/tiny_ttf/lv_tiny_ttf.c \
Lib/LVGL/lvgl/src/libs/tjpgd/lv_tjpgd.c \
Lib/LVGL/lvgl/src/libs/tjpgd/tjpgd.c \
Lib/LVGL/lvgl/src/lv_init.c \
Lib/LVGL/lvgl/src/misc/cache/lv_cache.c \
Lib/LVGL/lvgl/src/misc/cache/lv_cache_entry.c \
Lib/LVGL/lvgl/src/misc/cache/lv_cache_lru_rb.c \
Lib/LVGL/lvgl/src/misc/cache/lv_image_cache.c \
Lib/LVGL/lvgl/src/misc/cache/lv_image_header_cache.c \
Lib/LVGL/lvgl/src/misc/lv_anim.c \
Lib/LVGL/lvgl/src/misc/lv_anim_timeline.c \
Lib/LVGL/lvgl/src/misc/lv_area.c \
Lib/LVGL/lvgl/src/misc/lv_array.c \
Lib/LVGL/lvgl/src/misc/lv_async.c \
Lib/LVGL/lvgl/src/misc/lv_bidi.c \
Lib/LVGL/lvgl/src/misc/lv_circle_buf.c \
Lib/LVGL/lvgl/src/misc/lv_color.c \
Lib/LVGL/lvgl/src/misc/lv_color_op.c \
Lib/LVGL/lvgl/src/misc/lv_event.c \
Lib/LVGL/lvgl/src/misc/lv_fs.c \
Lib/LVGL/lvgl/src/misc/lv_iter.c \
Lib/LVGL/lvgl/src/misc/lv_ll.c \
Lib/LVGL/lvgl/src/misc/lv_log.c \
Lib/LVGL/lvgl/src/misc/lv_lru.c \
Lib/LVGL/lvgl/src/misc/lv_math.c \
Lib/LVGL/lvgl/src/misc/lv_matrix.c \
Lib/LVGL/lvgl/src/misc/lv_palette.c \
Lib/LVGL/lvgl/src/misc/lv_profiler_builtin.c \
Lib/LVGL/lvgl/src/misc/lv_rb.c \
Lib/LVGL/lvgl/src/misc/lv_style.c \
Lib/LVGL/lvgl/src/misc/lv_style_gen.c \
Lib/LVGL/lvgl/src/misc/lv_templ.c \
Lib/LVGL/lvgl/src/misc/lv_text.c \
Lib/LVGL/lvgl/src/misc/lv_text_ap.c \
Lib/LVGL/lvgl/src/misc/lv_timer.c \
Lib/LVGL/lvgl/src/misc/lv_tree.c \
Lib/LVGL/lvgl/src/misc/lv_utils.c \
Lib/LVGL/lvgl/src/osal/lv_cmsis_rtos2.c \
Lib/LVGL/lvgl/src/osal/lv_freertos.c \
Lib/LVGL/lvgl/src/osal/lv_mqx.c \
Lib/LVGL/lvgl/src/osal/lv_os.c \
Lib/LVGL/lvgl/src/osal/lv_pthread.c \
Lib/LVGL/lvgl/src/osal/lv_rtthread.c \
Lib/LVGL/lvgl/src/osal/lv_sdl2.c \
Lib/LVGL/lvgl/src/osal/lv_windows.c \
Lib/LVGL/lvgl/src/others/file_explorer/lv_file_explorer.c \
Lib/LVGL/lvgl/src/others/font_manager/lv_font_manager.c \
Lib/LVGL/lvgl/src/others/font_manager/lv_font_manager_recycle.c \
Lib/LVGL/lvgl/src/others/font_manager/lv_font_manager_utils.c \
Lib/LVGL/lvgl/src/others/fragment/lv_fragment.c \
Lib/LVGL/lvgl/src/others/fragment/lv_fragment_manager.c \
Lib/LVGL/lvgl/src/others/gridnav/lv_gridnav.c \
Lib/LVGL/lvgl/src/others/ime/lv_ime_pinyin.c \
Lib/LVGL/lvgl/src/others/imgfont/lv_imgfont.c \
Lib/LVGL/lvgl/src/others/monkey/lv_monkey.c \
Lib/LVGL/lvgl/src/others/observer/lv_observer.c \
Lib/LVGL/lvgl/src/others/snapshot/lv_snapshot.c \
Lib/LVGL/lvgl/src/others/sysmon/lv_sysmon.c \
Lib/LVGL/lvgl/src/others/vg_lite_tvg/vg_lite_matrix.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_base_types.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_component.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_parser.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_style.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_utils.c \
Lib/LVGL/lvgl/src/others/xml/lv_xml_widget.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_button_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_chart_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_image_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_label_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_obj_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_slider_parser.c \
Lib/LVGL/lvgl/src/others/xml/parsers/lv_xml_tabview_parser.c \
Lib/LVGL/lvgl/src/stdlib/builtin/lv_mem_core_builtin.c \
Lib/LVGL/lvgl/src/stdlib/builtin/lv_sprintf_builtin.c \
Lib/LVGL/lvgl/src/stdlib/builtin/lv_string_builtin.c \
Lib/LVGL/lvgl/src/stdlib/builtin/lv_tlsf.c \
Lib/LVGL/lvgl/src/stdlib/clib/lv_mem_core_clib.c \
Lib/LVGL/lvgl/src/stdlib/clib/lv_sprintf_clib.c \
Lib/LVGL/lvgl/src/stdlib/clib/lv_string_clib.c \
Lib/LVGL/lvgl/src/stdlib/lv_mem.c \
Lib/LVGL/lvgl/src/stdlib/micropython/lv_mem_core_micropython.c \
Lib/LVGL/lvgl/src/stdlib/rtthread/lv_mem_core_rtthread.c \
Lib/LVGL/lvgl/src/stdlib/rtthread/lv_sprintf_rtthread.c \
Lib/LVGL/lvgl/src/stdlib/rtthread/lv_string_rtthread.c \
Lib/LVGL/lvgl/src/themes/default/lv_theme_default.c \
Lib/LVGL/lvgl/src/themes/lv_theme.c \
Lib/LVGL/lvgl/src/themes/mono/lv_theme_mono.c \
Lib/LVGL/lvgl/src/themes/simple/lv_theme_simple.c \
Lib/LVGL/lvgl/src/tick/lv_tick.c \
Lib/LVGL/lvgl/src/widgets/animimage/lv_animimage.c \
Lib/LVGL/lvgl/src/widgets/arc/lv_arc.c \
Lib/LVGL/lvgl/src/widgets/bar/lv_bar.c \
Lib/LVGL/lvgl/src/widgets/button/lv_button.c \
Lib/LVGL/lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.c \
Lib/LVGL/lvgl/src/widgets/calendar/lv_calendar.c \
Lib/LVGL/lvgl/src/widgets/calendar/lv_calendar_chinese.c \
Lib/LVGL/lvgl/src/widgets/calendar/lv_calendar_header_arrow.c \
Lib/LVGL/lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c \
Lib/LVGL/lvgl/src/widgets/canvas/lv_canvas.c \
Lib/LVGL/lvgl/src/widgets/chart/lv_chart.c \
Lib/LVGL/lvgl/src/widgets/checkbox/lv_checkbox.c \
Lib/LVGL/lvgl/src/widgets/dropdown/lv_dropdown.c \
Lib/LVGL/lvgl/src/widgets/image/lv_image.c \
Lib/LVGL/lvgl/src/widgets/imagebutton/lv_imagebutton.c \
Lib/LVGL/lvgl/src/widgets/keyboard/lv_keyboard.c \
Lib/LVGL/lvgl/src/widgets/label/lv_label.c \
Lib/LVGL/lvgl/src/widgets/led/lv_led.c \
Lib/LVGL/lvgl/src/widgets/line/lv_line.c \
Lib/LVGL/lvgl/src/widgets/list/lv_list.c \
Lib/LVGL/lvgl/src/widgets/lottie/lv_lottie.c \
Lib/LVGL/lvgl/src/widgets/menu/lv_menu.c \
Lib/LVGL/lvgl/src/widgets/msgbox/lv_msgbox.c \
Lib/LVGL/lvgl/src/widgets/objx_templ/lv_objx_templ.c \
Lib/LVGL/lvgl/src/widgets/property/lv_dropdown_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_image_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_keyboard_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_label_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_obj_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_roller_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_style_properties.c \
Lib/LVGL/lvgl/src/widgets/property/lv_textarea_properties.c \
Lib/LVGL/lvgl/src/widgets/roller/lv_roller.c \
Lib/LVGL/lvgl/src/widgets/scale/lv_scale.c \
Lib/LVGL/lvgl/src/widgets/slider/lv_slider.c \
Lib/LVGL/lvgl/src/widgets/span/lv_span.c \
Lib/LVGL/lvgl/src/widgets/spinbox/lv_spinbox.c \
Lib/LVGL/lvgl/src/widgets/spinner/lv_spinner.c \
Lib/LVGL/lvgl/src/widgets/switch/lv_switch.c \
Lib/LVGL/lvgl/src/widgets/table/lv_table.c \
Lib/LVGL/lvgl/src/widgets/tabview/lv_tabview.c \
Lib/LVGL/lvgl/src/widgets/textarea/lv_textarea.c \
Lib/LVGL/lvgl/src/widgets/tileview/lv_tileview.c \
Lib/LVGL/lvgl/src/widgets/win/lv_win.c \
Lib/LVGL/lvgl/tests/makefile/test.c \
Lib/LVGL/lvgl/tests/makefile_uefi/test.c \
Lib/LVGL/lvgl/tests/src/lv_test_helpers.c \
Lib/LVGL/lvgl/tests/src/lv_test_indev.c \
Lib/LVGL/lvgl/tests/src/lv_test_init.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_animimg001.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_animimg002.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_animimg003.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_arc_bg.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_1.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_1_bin.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_2.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_2_bin.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_3.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_3_bin.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_montserrat_ascii_1bpp.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_montserrat_ascii_2bpp.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_montserrat_ascii_4bpp.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_font_montserrat_ascii_4bpp_compressed.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_imagebutton_left.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_imagebutton_mid.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_imagebutton_right.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_caret_down.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_a8.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_argb8888.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_i4.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_rgb565.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_rgb565a8.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_cogwheel_xrgb8888.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_emoji_F617.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_lvgl_logo_jpg.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_img_lvgl_logo_png.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_kern_one_otf.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_lottie_approve.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_music_button_play.c \
Lib/LVGL/lvgl/tests/src/test_assets/test_ubuntu_font.c \
Lib/LVGL/lvgl/tests/src/test_cases/_test_template.c \
Lib/LVGL/lvgl/tests/src/test_cases/cache/test_cache.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_bg_image.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_clip_corner.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_blend.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_label.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_layer.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_svg.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_sw_post_process.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_draw_vector.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_image_formats.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_layer_transform.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_al88.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_argb1555.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_argb2222.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_argb4444.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_argb8888.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_i1.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_l8.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_rgb565.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_rgb888.c \
Lib/LVGL/lvgl/tests/src/test_cases/draw/test_render_to_xrgb8888.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_barcode.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_bin_decoder.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_bmp.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_font_stress.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_freetype.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_libjpeg_turbo.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_libpng.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_lodepng.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_memmove.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_qrcode.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_tiny_ttf.c \
Lib/LVGL/lvgl/tests/src/test_cases/libs/test_tjpgd.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_align_flex.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_anim.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_anim_timeline.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_area.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_array.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_bindings.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_circle_buf.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_click.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_config.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_demo_stress.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_demo_widgets.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_display.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_draw_buf_stride.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_event.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_file_explorer.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_font_loader.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_fs.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_grid.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_grid_fr.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_gridnav.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_group.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_hover.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_margin_align.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_margin_flex.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_margin_grid.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_math.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_mem.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_observer.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_profiler.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_screen_load.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_snapshot.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_style.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_svg.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_svg_anim.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_tree.c \
Lib/LVGL/lvgl/tests/src/test_cases/test_txt.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_animimg.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_arc.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_bar.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_btn.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_btnmatrix.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_calendar.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_canvas.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_chart.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_checkbox.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_dropdown.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_image.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_imagebutton.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_imgfont.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_keyboard.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_label.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_led.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_line.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_list.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_lottie.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_msgbox.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_obj_flags.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_obj_pos.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_obj_property.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_obj_transform.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_obj_tree.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_objid.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_roller.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_scale.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_slider.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_span.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_spinbox.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_spinner.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_switch.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_table.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_tabview.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_textarea.c \
Lib/LVGL/lvgl/tests/src/test_cases/widgets/test_win.c \
Lib/LVGL/lvgl/tests/src/test_cases/xml/test_xml_general.c \
Lib/LVGL/lvgl/tests/src/test_cases/xml/test_xml_slider.c \
Lib/LVGL/lvgl/tests/src/test_libs/rnd_unicodes/lv_rnd_unicodes.c \
Lib/LVGL/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src/library.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_A1_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_A2_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_A4_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_A8_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_ARGB8888_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_I1_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_I2_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_I4_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_I8_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_L8_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_RGB565A8_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_RGB565_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_RGB888_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/LZ4/test_XRGB8888_LZ4_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_A1_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_A2_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_A4_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_A8_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_ARGB8888_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_I1_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_I2_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_I4_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_I8_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_L8_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_RGB565A8_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_RGB565_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_RGB888_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/RLE/test_XRGB8888_RLE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_A1_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_A2_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_A4_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_A8_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_ARGB8888_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_I1_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_I2_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_I4_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_I8_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_L8_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_RGB565A8_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_RGB565_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_RGB888_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align1/UNCOMPRESSED/test_XRGB8888_NONE_align1.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_A1_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_A2_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_A4_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_A8_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_ARGB8888_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_I1_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_I2_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_I4_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_I8_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_L8_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_RGB565A8_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_RGB565_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_RGB888_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/LZ4/test_XRGB8888_LZ4_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_A1_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_A2_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_A4_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_A8_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_ARGB8888_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_I1_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_I2_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_I4_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_I8_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_L8_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_RGB565A8_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_RGB565_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_RGB888_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/RLE/test_XRGB8888_RLE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_A1_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_A2_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_A4_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_A8_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_ARGB8888_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_I1_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_I2_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_I4_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_I8_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_L8_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_RGB565A8_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_RGB565_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_RGB888_NONE_align64.c \
Lib/LVGL/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_XRGB8888_NONE_align64.c \
Lib/LVGL/lvgl/tests/unity/unity.c \
Lib/LVGL/lvgl/tests/unity/unity_support.c \
Lib/PCA9555/pca9555.c \
Lib/SCan/SC24/artifacts/HVCB/c_source/hvcb.c \
Lib/SCan/SC24/artifacts/MCB/c_source/mcb.c \
Lib/STM32_HAL_ST7032_LCD_LIBRARY/STM32_ST7032.c


CPP_SOURCES = \
Lib/LVGL/lvgl/src/drivers/display/tft_espi/lv_tft_espi.cpp \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_arduino_esp_littlefs.cpp \
Lib/LVGL/lvgl/src/libs/fsdrv/lv_fs_arduino_sd.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgAccessor.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgAnimation.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgCanvas.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgCapi.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgCompressor.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgFill.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgGlCanvas.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgInitializer.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLoader.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieAnimation.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieBuilder.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieExpressions.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieInterpolator.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieLoader.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieModel.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieModifier.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieParser.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgLottieParserHandler.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgMath.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgPaint.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgPicture.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgRawLoader.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgRender.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSaver.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgScene.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgShape.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgStr.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSvgCssStyle.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSvgLoader.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSvgPath.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSvgSceneBuilder.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSvgUtil.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwCanvas.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwFill.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwImage.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwMath.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwMemPool.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwPostEffect.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwRaster.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwRenderer.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwRle.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwShape.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgSwStroke.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgTaskScheduler.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgText.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgWgCanvas.cpp \
Lib/LVGL/lvgl/src/libs/thorvg/tvgXmlParser.cpp \
Lib/LVGL/lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp


# ASM sources
ASM_SOURCES =  \
Lib/LVGL/lvgl/src/draw/sw/blend/helium/lv_blend_helium.S \
Lib/LVGL/lvgl/src/draw/sw/blend/neon/lv_blend_neon.S \
startup_stm32f446xx.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S

# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DLV_LVGL_H_INCLUDE_SIMPLE \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/ILI9488 \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IEEZ \
-IEEZ/src/ui \
-ILib/LVGL/callback \
-ILib/LVGL/log \
-ILib/LVGL/lvgl \
-ILib/LVGL/lvgl/src \
-ILib/PCA9555 \
-ILib/SCan/SC24/artifacts/HVCB/c_source \
-ILib/SCan/SC24/artifacts/MCB/c_source \
-ILib/STM32_HAL_ST7032_LCD_LIBRARY



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -specs=nano.specs -u_printf_float 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(subst ../,parent,$(1))))))

REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c md $(call convert_to_windows_path,$(1))
endif



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CPP_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

# the tree of folders which needs to be present based on the object files
BUILD_TREE = $(sort $(dir $(OBJECTS)))

# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(BUILD_TREE)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(BUILD_DIRECTORY)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIRECTORY)/%.hex: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(HEX) $< $@

$(BUILD_DIRECTORY)/%.bin: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(BIN) $< $@

$(BUILD_DIRECTORY)/%.lss: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(LSS) $< > $@

$(BUILD_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_TREE):
	$(call mkdir_function, $@)

#######################################
# all
#######################################
# default action: build all
all:
	$(BUILD_DIRECTORY)/$(TARGET).elf 
	$(BUILD_DIRECTORY)/$(TARGET).hex 
	$(BUILD_DIRECTORY)/$(TARGET).bin 
	$(BUILD_DIRECTORY)/$(TARGET).lss 


flash: $(BUILD_DIRECTORY)/$(TARGET).elf
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(BUILD_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIRECTORY)/$(TARGET).elf
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIRECTORY)/*.d)

# *** EOF ***